In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.preprocessing import OneHotEncoder

In [3]:
train_set = pd.read_csv('./dataset_diabetes/diabetic_data_train.csv')
ts = train_set.copy()
ts.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [4]:
for col in ts.columns:
    print(ts.groupby(col)[col].value_counts())

encounter_id  encounter_id
12522         12522           1
15738         15738           1
28236         28236           1
35754         35754           1
36900         36900           1
                             ..
443847548     443847548       1
443847782     443847782       1
443854148     443854148       1
443857166     443857166       1
443867222     443867222       1
Name: encounter_id, Length: 81412, dtype: int64
patient_nbr  patient_nbr
135          135            2
729          729            1
927          927            1
1152         1152           4
1305         1305           1
                           ..
189351095    189351095      1
189365864    189365864      1
189445127    189445127      1
189481478    189481478      1
189502619    189502619      1
Name: patient_nbr, Length: 60044, dtype: int64
race             race
?                ?                   1800
AfricanAmerican  AfricanAmerican    15384
Asian            Asian                528
Caucasian        Caucasian          60858
Hispanic         Hispanic            1613
Other            Other               1229
Name: race, dtype: int64
gender           gender
Female           Female             43769
Male             Male               37641
Unknown/Invalid  Unknown/Invalid        2
Name: gender, dtype: int64
age       age
[0-10)    [0-10)        122
[10-20)   [10-20)       560
[20-30)   [20-30)      1323
[30-40)   [30-40)      2975
[40-50)   [40-50)      7821
[50-60)   [50-60)     13753
[60-70)   [60-70)     18016
[70-80)   [70-80)     20831
[80-90)   [80-90)     13742
[90-100)  [90-100)     2269
Name: age, dtype: int64
weight     weight
>200       >200             3
?          ?            78849
[0-25)     [0-25)          40
[100-125)  [100-125)      504
[125-150)  [125-150)      119
[150-175)  [150-175)       31
[175-200)  [175-200)        7
[25-50)    [25-50)         76
[50-75)    [50-75)        716
[75-100)   [75-100)      1067
Name: weight, dtype: int64
admission_type_id  admission_type_id
1                  1                    43281
2                  2                    14748
3                  3                    15074
4                  4                        8
5                  5                     3819
6                  6                     4205
7                  7                       15
8                  8                      262
Name: admission_type_id, dtype: int64
discharge_disposition_id  discharge_disposition_id
1                         1                           48120
2                         2                            1714
3                         3                           11160
4                         4                             677
5                         5                             969
6                         6                           10351
7                         7                             502
8                         8                              85
9                         9                              17
10                        10                              5
11                        11                           1319
12                        12                              2
13                        13                            318
14                        14                            288
15                        15                             51
16                        16                              9
17                        17                              9
18                        18                           2938
19                        19                              6
20                        20                              2
22                        22                           1582
23                        23                            326
24                        24                             42
25                        25                            794
27                        27                              4
28                        28                            122
Name: discharge_disposition_id, dtype: int64
admission_source_id  admission_source_id
1                    1                      23669
2                    2                        872
3                    3                        144
4                    4                       2508
5                    5                        675
6                    6                       1805
7                    7                      46106
8                    8                         14
9                    9                         94
10                   10                         8
11                   11                         2
13                   13                         1
14                   14                         2
17                   17                      5369
20                   20                       134
22                   22                         8
25                   25                         1
Name: admission_source_id, dtype: int64
time_in_hospital  time_in_hospital
1                 1                   11432
2                 2                   13806
3                 3                   14130
4                 4                   11132
5                 5                    7948
6                 6                    6017
7                 7                    4705
8                 8                    3535
9                 9                    2434
10                10                   1894
11                11                   1480
12                12                   1130
13                13                    950
14                14                    819
Name: time_in_hospital, dtype: int64
payer_code  payer_code
?           ?             32138
BC          BC             3671
CH          CH              123
CM          CM             1565
CP          CP             2053
DM          DM              441
HM          HM             5074
MC          MC            26000
MD          MD             2827
MP          MP               61
OG          OG              819
OT          OT               80
PO          PO              463
SI          SI               41
SP          SP             3984
UN          UN             1957
WC          WC              115
Name: payer_code, dtype: int64
medical_specialty                 medical_specialty
?                                 ?                                   40063
AllergyandImmunology              AllergyandImmunology                    6
Anesthesiology                    Anesthesiology                         11
Anesthesiology-Pediatric          Anesthesiology-Pediatric               15
Cardiology                        Cardiology                           4274
                                                                      ...
Surgery-PlasticwithinHeadandNeck  Surgery-PlasticwithinHeadandNeck        1
Surgery-Thoracic                  Surgery-Thoracic                       93
Surgery-Vascular                  Surgery-Vascular                      424
SurgicalSpecialty                 SurgicalSpecialty                      29
Urology                           Urology                               535
Name: medical_specialty, Length: 72, dtype: int64
num_lab_procedures  num_lab_procedures
1                   1                     2599
2                   2                      884
3                   3                      551
4                   4                      301
5                   5                      232
                                          ...
118                 118                      1
120                 120                      1
126                 126                      1
129                 129                      1
132                 132                      1
Name: num_lab_procedures, Length: 117, dtype: int64
num_procedures  num_procedures
0               0                 37447
1               1                 16518
2               2                 10154
3               3                  7500
4               4                  3361
5               5                  2456
6               6                  3976
Name: num_procedures, dtype: int64
num_medications  num_medications
1                1                   205
2                2                   367
3                3                   728
4                4                  1137
5                5                  1623
                                    ...
72               72                    3
74               74                    1
75               75                    2
79               79                    1
81               81                    1
Name: num_medications, Length: 75, dtype: int64
number_outpatient  number_outpatient
0                  0                    67997
1                  1                     6840
2                  2                     2887
3                  3                     1635
4                  4                      884
5                  5                      437
6                  6                      233
7                  7                      122
8                  8                       76
9                  9                       67
10                 10                      50
11                 11                      34
12                 12                      23
13                 13                      28
14                 14                      23
15                 15                      18
16                 16                      12
17                 17                       5
18                 18                       4
19                 19                       2
20                 20                       5
21                 21                       5
22                 22                       5
23                 23                       2
24                 24                       2
25                 25                       1
26                 26                       2
27                 27                       2
28                 28                       1
29                 29                       2
34                 34                       1
35                 35                       1
36                 36                       2
37                 37                       1
39                 39                       1
40                 40                       1
42                 42                       1
Name: number_outpatient, dtype: int64
number_emergency  number_emergency
0                 0                   72340
1                 1                    6086
2                 2                    1653
3                 3                     586
4                 4                     303
5                 5                     150
6                 6                      72
7                 7                      61
8                 8                      42
9                 9                      25
10                10                     28
11                11                     16
12                12                      8
13                13                      8
14                14                      3
15                15                      2
16                16                      4
18                18                      5
19                19                      4
20                20                      3
21                21                      2
22                22                      5
24                24                      1
25                25                      2
46                46                      1
54                54                      1
64                64                      1
Name: number_emergency, dtype: int64
number_inpatient  number_inpatient
0                 0                   53972
1                 1                   15705
2                 2                    6067
3                 3                    2745
4                 4                    1309
5                 5                     641
6                 6                     391
7                 7                     212
8                 8                     120
9                 9                      92
10                10                     52
11                11                     35
12                12                     29
13                13                     18
14                14                      8
15                15                      7
16                16                      5
18                18                      1
19                19                      2
21                21                      1
Name: number_inpatient, dtype: int64
diag_1  diag_1
10      10         1
11      11         6
110     110        2
112     112       62
114     114        1
                  ..
V60     V60        1
V63     V63        8
V66     V66        2
V67     V67        1
V71     V71        7
Name: diag_1, Length: 697, dtype: int64
diag_2  diag_2
11      11          3
110     110         6
111     111         1
112     112       148
114     114         1
                 ...
V69     V69         1
V70     V70         5
V72     V72        10
V85     V85       133
V86     V86         1
Name: diag_2, Length: 716, dtype: int64
diag_3  diag_3
11      11          1
110     110        14
111     111         1
112     112       171
115     115         1
                 ...
V66     V66        15
V70     V70         2
V72     V72         7
V85     V85        76
V86     V86         3
Name: diag_3, Length: 768, dtype: int64
number_diagnoses  number_diagnoses
1                 1                     168
2                 2                     802
3                 3                    2274
4                 4                    4436
5                 5                    9057
6                 6                    8163
7                 7                    8328
8                 8                    8505
9                 9                   39591
10                10                     14
11                11                      9
12                12                      6
13                13                     13
14                14                      5
15                15                      8
16                16                     33
Name: number_diagnoses, dtype: int64
max_glu_serum  max_glu_serum
>200           >200              1195
>300           >300               998
None           None             77158
Norm           Norm              2061
Name: max_glu_serum, dtype: int64
A1Cresult  A1Cresult
>7         >7            3019
>8         >8            6570
None       None         67814
Norm       Norm          4009
Name: A1Cresult, dtype: int64
metformin  metformin
Down       Down           459
No         No           65485
Steady     Steady       14623
Up         Up             845
Name: metformin, dtype: int64
repaglinide  repaglinide
Down         Down              30
No           No             80172
Steady       Steady          1126
Up           Up                84
Name: repaglinide, dtype: int64
nateglinide  nateglinide
Down         Down              10
No           No             80841
Steady       Steady           539
Up           Up                22
Name: nateglinide, dtype: int64
chlorpropamide  chlorpropamide
Down            Down                  1
No              No                81341
Steady          Steady               66
Up              Up                    4
Name: chlorpropamide, dtype: int64
glimepiride  glimepiride
Down         Down             155
No           No             77257
Steady       Steady          3749
Up           Up               251
Name: glimepiride, dtype: int64
acetohexamide  acetohexamide
No             No               81411
Steady         Steady               1
Name: acetohexamide, dtype: int64
glipizide  glipizide
Down       Down           453
No         No           71287
Steady     Steady        9063
Up         Up             609
Name: glipizide, dtype: int64
glyburide  glyburide
Down       Down           452
No         No           72892
Steady     Steady        7426
Up         Up             642
Name: glyburide, dtype: int64
tolbutamide  tolbutamide
No           No             81395
Steady       Steady            17
Name: tolbutamide, dtype: int64
pioglitazone  pioglitazone
Down          Down               98
No            No              75526
Steady        Steady           5599
Up            Up                189
Name: pioglitazone, dtype: int64
rosiglitazone  rosiglitazone
Down           Down                68
No             No               76343
Steady         Steady            4859
Up             Up                 142
Name: rosiglitazone, dtype: int64
acarbose  acarbose
Down      Down            3
No        No          81167
Steady    Steady        234
Up        Up              8
Name: acarbose, dtype: int64
miglitol  miglitol
Down      Down            3
No        No          81381
Steady    Steady         27
Up        Up              1
Name: miglitol, dtype: int64
troglitazone  troglitazone
No            No              81409
Steady        Steady              3
Name: troglitazone, dtype: int64
tolazamide  tolazamide
No          No            81380
Steady      Steady           31
Up          Up                1
Name: tolazamide, dtype: int64
examide  examide
No       No         81412
Name: examide, dtype: int64
citoglipton  citoglipton
No           No             81412
Name: citoglipton, dtype: int64
insulin  insulin
Down     Down        9725
No       No         37967
Steady   Steady     24602
Up       Up          9118
Name: insulin, dtype: int64
glyburide-metformin  glyburide-metformin
Down                 Down                       5
No                   No                     80834
Steady               Steady                   567
Up                   Up                         6
Name: glyburide-metformin, dtype: int64
glipizide-metformin  glipizide-metformin
No                   No                     81402
Steady               Steady                    10
Name: glipizide-metformin, dtype: int64
glimepiride-pioglitazone  glimepiride-pioglitazone
No                        No                          81412
Name: glimepiride-pioglitazone, dtype: int64
metformin-rosiglitazone  metformin-rosiglitazone
No                       No                         81411
Steady                   Steady                         1
Name: metformin-rosiglitazone, dtype: int64
metformin-pioglitazone  metformin-pioglitazone
No                      No                        81412
Name: metformin-pioglitazone, dtype: int64
change  change
Ch      Ch        37472
No      No        43940
Name: change, dtype: int64
diabetesMed  diabetesMed
No           No             18742
Yes          Yes            62670
Name: diabetesMed, dtype: int64
readmitted  readmitted
<30         <30            9154
>30         >30           28517
NO          NO            43741
Name: readmitted, dtype: int64